# Generated by Django 6.1 on 2026-09-20 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('general', 'General Physician'), ('cardiology', 'Cardiologist'), ('dermatology', 'Dermatologist'), ('orthopedic', 'Orthopedic'), ('pediatrician', 'Pediatrician'), ('gynecology', 'Gynecologist'), ('dentist', 'Dentist'), ('neurology', 'Neurologist'), ('other', 'Other')], default='general', max_length=50)),
                ('qualification', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Experience in years')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_days', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
